### ISSUE TITLE
Possible to put instructions in stderr and custom attributes in stdout?

### ISSUE THREAD

**Issue by dhoile** [danieldreier/autosign#8]
We'd like to be able to have the instructions that are generated when running autosign to generate a token redirected to stderr and the token info itself sent to stdout so we don't have to parse the instructions out.  (we're lazy)

Context: Automate generation of token without having to parse instructions out of returned string.

**Comment by danieldreier** [comment]
that makes sense -- would it be sufficient to simply add a flag that generates a bare token without the surrounding csr_attributes yaml stuff?

**Comment by dhoile** [comment]
That would be an excellent solution for us.

This is our current workaround:

/opt/puppet/bin/autosign generate foo.example.com | awk '{if (NR > 3) {print $0}}'

I sat in your presentation a few user groups ago and we are already actively using your module to automate our VM deploys via UCSD, and are very happy.  See you at PuppetConf?

**Comment by danieldreier** [comment]
PR https://github.com/danieldreier/autosign/issues/13 should resolve this - I'd appreciate a review when you've got a chance.

**Comment by danieldreier** [comment]
@dhoile I've published 0.1.0 to rubygems which includes the new --bare flag. I believe that this resolves the issue so I'm closing it, but please feel free to re-open it if there are issues you run into.
